export enum AssessmentQuestionServiceActions {
  SUCCESSFUL_DOMAIN_CREATION,
  UNSUCCESSFUL_DOMAIN_CREATION,
  SUCCESSFUL_AGE_GROUP_CREATION,
  UNSUCCESSFUL_AGE_GROUP_CREATION,
  SUCCESSFUL_MAIN_QUESTION_CREATION,
  UNSUCCESSFUL_MAIN_QUESTION_CREATION,
  SUCCESSFUL_SUB_MODULE_CREATION,
  UNSUCCESSFUL_SUB_MODULE_CREATION,
  SUCCESSFUL_SUB_QUESTION_CREATION,
  UNSUCCESSFUL_SUB_QUESTION_CREATION,
}
